Add option for exiting with non-zero code on error logs

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -21,6 +21,10 @@ inputs:
   env_file:
     description: Possible path to environment file to use
     required: false
+  catch_error_logs:
+    description: Catch error logs and fail the action if found. Defaults to false.
+    required: false
+    default: "false"
 
 runs:
   using: "composite"
@@ -117,4 +121,15 @@ runs:
           "ghcr.io/home-assistant/home-assistant:${{ steps.version.outputs.version }}" \
             python -m homeassistant \
               --config "${{ steps.check.outputs.path }}" \
-              --script check_config
+              --script check_config > "${{ github.workspace }}/configuration_check.log" 2>&1
+
+    - name: 🥅 Catch Error Logs
+      shell: bash
+      if: ${{ inputs.catch_error_logs != 'false' }}
+      run: |
+        if grep -q "^ERROR:" "${{ github.workspace }}/configuration_check.log"; then
+          cat "${{ github.workspace }}/configuration_check.log" > "${GITHUB_STEP_SUMMARY}"
+
+          echo "::error ::Home Assistant Configuration Check failed"
+          exit 1
+        fi
