Add ignore pattern

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -25,6 +25,10 @@ inputs:
     description: Catch error logs and fail the action if found. Defaults to false.
     required: false
     default: "false"
+  ignore_error_log_pattern:
+    description: Any error logs matching this regex pattern will be ignored. Defaults to empty.
+    required: false
+    default: ""
 
 runs:
   using: "composite"
@@ -128,13 +132,22 @@ runs:
       shell: bash
       if: ${{ inputs.catch_error_logs != 'false' }}
       env:
+        IGNORE_PATTERN: ${{ inputs.ignore_error_log_pattern }}
         LOG_FILE: "${{ github.workspace }}/configuration_check.log"
       run: |
         if grep -q "^ERROR:" "${LOG_FILE}"; then
-          echo -e "\`\`\`\n" >> "${GITHUB_STEP_SUMMARY}"
-          cat "${LOG_FILE}" >> "${GITHUB_STEP_SUMMARY}"
-          echo -e "\n\`\`\`" >> "${GITHUB_STEP_SUMMARY}"
+          ERROR_LINES=$(grep "^ERROR:" "${LOG_FILE}")
+          
+          if [[ -n "${IGNORE_PATTERN}" ]]; then
+            ERROR_LINES=$(echo "${ERROR_LINES}" | grep -vP "${IGNORE_PATTERN}")
+          fi
 
-          echo "::error ::Home Assistant Configuration Check failed"
-          exit 1
+          if [[ -n "${ERROR_LINES}" ]]; then
+            echo -e "\`\`\`" >> "${GITHUB_STEP_SUMMARY}"
+            echo "${ERROR_LINES}" >> "${GITHUB_STEP_SUMMARY}"
+            echo -e "\`\`\`" >> "${GITHUB_STEP_SUMMARY}"
+
+            echo "::error ::Home Assistant Configuration Check failed"
+            exit 1
+          fi
         fi
